# Generated by Django 3.2.3 on 2021-05-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
