# Generated by Django 3.2.3 on 2021-05-29 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanager', '0003_alter_info_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 29, 13, 51, 26, 324073)),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
