# Generated by Django 3.2.3 on 2021-06-02 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanager', '0004_auto_20210529_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 2, 11, 9, 12, 855914)),
        ),
    ]
