# Generated by Django 3.2.3 on 2021-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomanager', '0006_alter_info_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gender',
            field=models.IntegerField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male'),
        ),
    ]
